### ISSUE TITLE
Cannot switch yarn version

### ISSUE THREAD

**Issue by mradkov** [tophat/yvm#1006]
<img width="422" alt="Screenshot 2021-11-26 at 11 27 41" src="https://user-images.githubusercontent.com/13139371/143558203-6922a49e-5301-4067-83a9-28c934069a54.png">

**Comment by noahnu** [comment]
`yvm version` shows the version of yvm, not yarn. To get the yarn version, you can just run `yarn --version`.

Regarding yarn 3, it's working as expected. Your project is using yarn 3, likely committed to the repo. Yvm controls the yarn 1 version. Your yarn 1 binary launches yarn 3 when it detects it in the yarnrc file. It's forwarding the version flag to yarn berry.
