### ISSUE TITLE
Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by DMackintosh-TNL** [tophat/yvm#1007]
**Describe the bug**
This message is dispayed whenever YVM is installed or brew is run, once the YVM repo is untapped then the message goes away.

**To Reproduce**
1. Install YVM via `brew install tophat/bar/yvm --without-node` or `brew install tophat/bar/yvm`
2. You will see the error `Error Calling bottle :unneeded is deprecated! There is no replacement.` in the output

**Expected behavior**
Shouldn't see this at all if the repo is up to date

**Screenshots**

**Desktop (please complete the following information):**
 - YVM Version: [e.g. 2018-12-02T19-19-12.205Z], you can get this from `yvm version`
 - Shell: [e.g. bash/sh/zsh/fish]
 - Node version: [e.g. v8.10.0], from `node --version`

**Additional context**
If you do a `brew doctor` or `brew update/upgrade` this popsup as well

**Comment by technicalpickles** [comment]
The code for this is over in tophat/homebrew-bar, and there's an issue for it already: https://github.com/tophat/homebrew-bar/issues/48

**Comment by noahnu** [comment]
Fixed in https://github.com/tophat/homebrew-bar/pull/49
