### ISSUE TITLE
Installing yarn with homebrew: Error: invalid option: --without-node

### ISSUE THREAD

**Issue by spacejamjim** [tophat/yvm#1008]
**Describe the bug**
When running: `brew install tophat/bar/yvm --without-node` I receive an error
`Error: invalid option: --without-node`

**To Reproduce**
❯ nvm -v
0.39.1
❯ node -v
v16.13.1
❯ brew --version
Homebrew 3.3.9
❯ brew install tophat/bar/yvm --without-node
... homebrew updating stuff ...
Error: invalid option: --without-node

**Expected behavior**
Should install yvm

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - Shell: zsh
 - Node version: 16.13.1

**Comment by sinau123** [comment]
i have the same issue. Any solutions?

**Comment by noahnu** [comment]
Looks like the same underlying problem as https://github.com/yarnpkg/yarn/issues/6946

**Comment by iamogbz** [comment]
You can workaround this by first tapping the bar and then installing
```sh
brew tap tophat/bar
brew install yvm --without-node
```

Although I then ran into some other issue
```sh
Failed to execute: node
```

Removing the `--without-node` solve all the installation issues on my end, but it seems like a Homebrew issue unrelated to the yvm formula

**Comment by noahnu** [comment]
The yvm project has been deprecated in favour of corepack which is distributed with NodeJS v14+. This repository is being archived as part of general open source maintenance and cleanup in this org.
