### ISSUE TITLE
How to uninstall yvm?

### ISSUE THREAD

**Issue by luciomartinez** [tophat/yvm#1009]
I tried with the following but didn't work:
```
% brew rm yvm
Error: No available formula or cask with the name "yvm". Did you mean nvm or dvm?
% brew rm tophat/bar/yvm
Error: No available formula or cask with the name "tophat/bar/yvm".
Please tap it and then try again: brew tap tophat/bar
```

The `--help` command shows these two options but none of them seems to _uninstall_ the package:
```
deactivate                          Undo effects of `yvm` on current shell
unload                              Unload `yvm` from shell
```

**Comment by noahnu** [comment]
It depends on how you installed it. If you used the install script rather than brew, you can first run `yvm unload` and then `rm -rf ~/.yvm`.

**Comment by luciomartinez** [comment]
That did the trick! I've also followed the steps at the [Readme's remove](https://github.com/tophat/yvm#removing). Thank you
