### ISSUE TITLE
Highlight currently active Yarn version in `yvm list` and `yvm list-remote`

### ISSUE THREAD

**Issue by umar-tophat** [tophat/yvm#101]
**Is your feature request related to a problem? Please describe.**
If I have multiple versions of Yarn installed and I want to switch from one to another, I have to first run `yvm which` to determine which version I am currently using. Then I have to remember this version, and run `yvm list` to see what versions are installed. This requires more cognitive overhead than should be required for a tool like this.

**Describe the solution you'd like**
When you run `yvm list` or `yvm list-remote`, the currently active version should be highlighted with a different color AND an arrow should be pointing to it like in nvm (see screenshot below).

**Describe alternatives you've considered**
An alternate solution is to simply add a line at the beginning or end of the version output that states what version is currently being used. This approach is not the best because there is a lot of info being printed on the screen in these commands, so it is likely to be missed.

**Additional context**

![nvm list output](https://user-images.githubusercontent.com/38886386/41938315-bcc533a4-7960-11e8-8287-8ed7d80838a4.png)

**Comment by sanchitgera** [comment]
Fixed ls-remote in #248
