### ISSUE TITLE
Verify integrity of tarball

### ISSUE THREAD

**Issue by umar-tophat** [tophat/yvm#102]
**Is your feature request related to a problem? Please describe.**
In order to reach parity with the Yarn install script (linked below), we should verify the integrity of the downloaded tarball.

**Describe the solution you'd like**
If the user has GPG installed, run the integrity check by downloading the public key, spawning a child process, and running GPG. If there is an error in the integrity check or GPG is not installed, notify the user, and prompt the user on whether or not to continue without verifying. Clean up the downloaded files regardless.

**Describe alternatives you've considered**
YOLO it and download tarballs from who knows where without verifying integrity (I am being sarcastic :neutral_face:).

**Additional context**
https://github.com/yarnpkg/website/blob/master/install.sh#L50

**Comment by jakebolam** [comment]
Shipped in https://github.com/tophat/yvm/pull/131
