### ISSUE TITLE
Getting a segfault when trying to do a `yarn install` using yvm

### ISSUE THREAD

**Issue by tgrant59** [tophat/yvm#103]
**Describe the bug**
When I run `yarn install` with `yvm` I'm getting a segfault:

```
75162/91112/Users/******/.yvm/yvm.sh: line 82: 60566 Segmentation fault: 11  node "${YVM_DIR}/yvm.js" $@
make: *** [node_modules] Error 139
```

**Comment by jakebolam** [comment]
@tgrant59 can you provide reproduce steps?

**Comment by tgrant59** [comment]
Clone fe-marketplace
run make install

**Comment by jakebolam** [comment]
Any more insight? 
<img width="826" alt="screen shot 2018-06-28 at 10 45 49 am" src="https://user-images.githubusercontent.com/3534236/42041711-744d37be-7ac0-11e8-9526-7b206369adad.png">

**Comment by msrose** [comment]
FWIW I did this earlier today and got no segfault, everything seemed find.

**Comment by tgrant59** [comment]
Was weird, I could reproduce it every time on that shell, but when I opened a new one, it disappeared FOREVER. Closing
