### ISSUE TITLE
`yvm.js.org` should be updated to include deprecation notice

### ISSUE THREAD

**Issue by samwinslow** [tophat/yvm#1036]
Hi there, I noticed there is no deprecation notice on this project's website, even though https://yvm.js.org/docs/overview seems to include content from README.md which does contain such a notice.

It would reduce confusion for many people who, like me, followed the instructions to install with `brew` without necessarily viewing the repo first.

Hopefully this is as simple as re-deploying the site.

**Comment by noahnu** [comment]
It should have deployed with that Feb 20th commit. Something is broken in the website deploy, I'll take a look.

**Comment by noahnu** [comment]
Updated
