### ISSUE TITLE
Idea: use exec instead of __non_webpack_require__

### ISSUE THREAD

**Issue by dat2** [tophat/yvm#111]
Instead of requiring the yarn bin js file, lets `exec` the yarn command.

If yarn ever changes their entry point to a shell script instead of a js file, we will suddenly stop working 😞

**Comment by msrose** [comment]
https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by jakebolam** [comment]
in #213, released in v0.9.3: https://github.com/tophat/yvm/releases/tag/v0.9.3
