### ISSUE TITLE
yvm does not set a default global yarn version

### ISSUE THREAD

**Issue by francoiscampbell** [tophat/yvm#127]
**Describe the bug**
If you don't have a global version of yarn installed, yvm does not provide one, so `yarn` in any shell does not work until doing `yvm use`, and even then, it only persists for the current shell.

**To Reproduce**
- Do not have a global version of yarn installed
- Run `yvm install <any version>`
- `yarn -v` works
- Open a new shell
- `yarn -v` is an unrecognized command
- `yvm use <the installed version>`
- `yarn -v` works

**Expected behavior**
- Do not have a global version of yarn installed
- Run `yvm install <any version>`, this installs this version of yarn as default
- `yarn -v` works
- Open a new shell
- `yarn -v` uses the same version as above automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - YVM Release: any

**Comment by francoiscampbell** [comment]
somewhat related to #56

**Comment by brandonbaksh** [comment]
Please refer to #137
