### ISSUE TITLE
Shimming the yarn command

### ISSUE THREAD

**Issue by dat2** [tophat/yvm#134]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have the `yarn` command automatically get `use`d depending on the folder i'm in! I get frustrated when I have to `yvm use` every time I open a new terminal.

**Describe the solution you'd like**
Similar to `pyenv` when you `cd` into a directory that has the `.yvmrc` file in it, and the yarn version specified is installed, shim the `yarn` command to be automatically `use`d.

Example:

`my-project-1` uses yarn `1.7.0`
```
➜ cd my-project-1
➜ cat .yvmrc
1.7.0
➜ yarn --version
1.7.0
```

`my-project-2` uses yarn `1.2.0`
```
➜ cd ../my-project-2
➜ cat .yvmrc
1.2.0
➜ yarn --version
1.2.0
```

I don't have yarn installed globally
```
➜ cd ..
➜ yarn --version
zsh: command not found: yarn
```

**Describe alternatives you've considered**
nothing 🙃 

**Additional context**

**Comment by brandonbaksh** [comment]
Please refer to #136
