### ISSUE TITLE
Use MANAGED BLOCK markers in rc files

### ISSUE THREAD

**Issue by francoiscampbell** [tophat/yvm#135]
**Is your feature request related to a problem? Please describe.**
The YVM block in rc files can be ambiguous or hard to locate

**Describe the solution you'd like**
It should be clear that the lines that are added to the user's rc file come from YVM

**Additional context**
For example, this is what https://github.com/pyenv/pyenv does:
```
# BEGIN pyenv MANAGED BLOCK
export PYENV_ROOT=~/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"
# END pyenv MANAGED BLOCK
```

**Comment by brandonbaksh** [comment]
Please refer to #136
