### ISSUE TITLE
Automatically use .yvmrc upon entering a directory

### ISSUE THREAD

**Issue by brandonbaksh** [tophat/yvm#136]
**Is your feature request related to a problem? Please describe.**
When working with multiple projects that utilize different versions of yarn, I always have to type `yvm use` in order to have yvm set the correct version of yarn that my project has. 

**Describe the solution you'd like**
When I switch into a directory that already has a `.yvmrc` file, I would like yvm to automatically run `yvm use` so that I don't have to do it manually.

**Comment by jaredscheib** [comment]
I like this idea. Another option would be, if there is no `.yvmrc` file, trying to read from `engines.yarn` in `package.json`? That might avoid the duplication of the same data, in case it already exists there.

**Comment by mlunoe** [comment]
The suggested proposal follows the same pattern as `.nvmrc`.
Using `package.json`s engines entry should probably be listed as a separate issue. See the discussion on the matter here for nvm, which is still not resolved: https://github.com/creationix/nvm/issues/651

**Comment by jakebolam** [comment]
@jaredscheib adding the concept of a global yarn version in PR #189.

I like the idea of reading from package.json as a fallback too (before falling back to global)

Want to add an issue? And maybe even put up a PR?

**Comment by jakebolam** [comment]
@aeldamaty has pointed out, this issue would be fixed by shimming the yarn command see #163

**Comment by jakebolam** [comment]
@jaredscheib @mlunoe `yvm` actually has support for package.json. This is buried in the docs:
https://yvm.js.org/docs/faq#declare-yvm-version-in-a-configuration-file-where-can-i-place-my-version-number

**Comment by jakebolam** [comment]
Feel free to come join us in the `yvm` channel on the slack workspace:
https://opensource.tophat.com/slack/

**Comment by mlunoe** [comment]
Thank you @jakebolam! Those docs, however, are a bit confusing.
But looking through the commit history I found [this commit](https://github.com/tophat/yvm/commit/8e1f7ed3b38016abbc3e9a7759bf73a7346c983a#diff-0486eddb45caf6e590f382c77f9efa29R10) that introduces the use of [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), which means we can set the version number under the `yvm` key in `package.json` - got it 👍.

What is confusing is that it mentions the other files in a separate sentence and it is not clear whether you need to do both, but understanding it now I see that you don't

**Comment by mlunoe** [comment]
I created a PR to update the docs here: https://github.com/tophat/yvm/pull/201

**Comment by torinthiel** [comment]
Note that this may have undesired side effect - given that `yvm use` automatically downloads version, we end up downloading stuff on a simple `cd`. And even if user has that version downloaded, we still end up displaying a message about currently used version. Even if it's the same version as used previously (imagine what happens when user types `cd ..` 3 times)

**Comment by mlunoe** [comment]
Oh wow. Why does it automatically download a version when you type `yvm use`? That does not seem like expected behavior. I would expect it to tell me if a version is not installed and bail out.

**Comment by yashshah** [comment]
I think we should let the user know if the version is not installed, and then give a prompt asking if they would like to download it.

**Comment by Grawl** [comment]
@yashshah it's not expected when you just `cd ..`

I think just prompt will be good:

```
$ cd ../
YVM: Trying to switch Yarn version to 1.12.1, but it's not installed. Run `yvm use` to install and apply Yarn 1.12.1
$
```

**Comment by noahnu** [comment]
I feel like this feature should be opt-in. E.g. `yvm install-cd-hook` would install the necessary bash configuration to do the auto `yvm use`.

Having this as default behaviour could produce undesirable side effects and produce potential vulnerabilities.
