### ISSUE TITLE
Add Greenkeeper to yvm 

### ISSUE THREAD

**Issue by brandonbaksh** [tophat/yvm#139]
**Is your feature request related to a problem? Please describe.**
When working on yvm, I am not sure about any security issues and compatibility issues with my package dependencies. 

**Describe the solution you'd like**
Add Greenkeeper to yvm in order to have visibility on updates for npm dependencies.

**Additional context**
https://greenkeeper.io/

**Comment by jakebolam** [comment]
Fixed in #164
