### ISSUE TITLE
Add support for --latest, --stable/--lts, etc.

### ISSUE THREAD

**Issue by jaredscheib** [tophat/yvm#175]
**Describe the solution you'd like**
Something I love about `nvm` is that you can have it install `--latest` and `--lts` versions of `node`. This would be a great feature to see here, for convenience. `--stable` could be used instead of `--lts` in this case.

**Describe alternatives you've considered**
Currently I have to research what the latest or stable versions of `yarn` are.

**Comment by brandonbaksh** [comment]
Hey Jared! Thanks for the awesome suggestion 👍

In the mean time you might find `yvm list-remote` helpful for finding the latest version!

**Comment by jakebolam** [comment]
@jaredscheib are you interested in implementing this?

**Comment by sanchitgera** [comment]
Added support for `yvm install --latest in #253

**Comment by jaredscheib** [comment]
Awesome -- thanks, y'all!
