### ISSUE TITLE
yvm list should show the default global version

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#193]
**Is your feature request related to a problem? Please describe.**
`yvm list` should show the default global version

**Describe the solution you'd like**
The default global version to appear in the list

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by yashshah** [comment]
I wanted to understand the issue correctly, does it mean to add helper text in the `yvm list` as shown in image below?
![image](https://user-images.githubusercontent.com/1558352/49506546-55a4f880-f8a4-11e8-99df-4328e9cc5f9d.png)

**Comment by jakebolam** [comment]
@yashshah yes!

There may be cases where the global version is not installed. We may also want to handle that? (haven't thought about where to do this yet tho).

**Comment by jakebolam** [comment]
Had to revert this in #235 as a circular import was causing issues #229: 

We've now added CI protection against this in #234.

Sorry @yashshah will have to try this again :)
