### ISSUE TITLE
auto infer version (instead of expecting in exact format)

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#194]
**Is your feature request related to a problem? Please describe.**
There's currently a long list of non-supported versions where we can easily infer the correct version. We could automatically infer the correct version to make yvm more user friendly

**Describe the solution you'd like**
Infer the correct version, and move a bunch of these invalid version cases, to the valid version cases:
https://github.com/tophat/yvm/blob/master/test/util/version.test.js#L38

**Describe alternatives you've considered**
Not doing it

**Additional context**

**Comment by yashshah** [comment]
I like the idea of automatically inferring the correct version from the string given.

`\d+(\.\d+)+` should give us the version number from any string. It will work great with the case `v1.5.0` to extract `1.5.0`. 

If we are looking to support only "Major.Minor.Build", we can do `\d+(\.\d+){1,2}` what are your thoughts?

**Comment by jakebolam** [comment]
@yashshah great idea! sounds good to me! Let's do it

**Comment by yashshah** [comment]
Just adding notes here:
It should also give fair warning when it cannot infer the version. Currently it is acting quite weirdly.
![image](https://user-images.githubusercontent.com/1558352/49801344-ee89b700-fd6f-11e8-9b87-cfddc2ab35e4.png)

**Comment by jakebolam** [comment]
@yashshah it totally should. 👍
