### ISSUE TITLE
YVM fails to install, because it requires write permissions to /usr/local/bin

### ISSUE THREAD

**Issue by torinthiel** [tophat/yvm#204]
**Describe the bug**
The official installation instructions require write permissions to `/usr/local/bin`, and do not inform of it nor of any methods to override, thus making it impossible to install without downloading and inspecting/tweaking the installation file.

**To Reproduce**
1. Run official installation instructions: `curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.sh | bash`
2. See error:
```Installing Version: 2018-12-07T00-24-10.408Z
ln: failed to create symbolic link '/usr/local/bin/yvm': Permission denied
yvm failed to install, the command that failed was: https://github.com/tophat/yvm/blob/master/scripts/install.sh#L50
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, docker image fedora:28
 - YVM Version: not installed, trying to install 2018-12-07T00-24-10.408Z
 - Shell: bash
 - Node version: v10.14.1

**Additional context**
Note that installing the files below $HOME, accessible to only one user, and symlinking that in /usr/local/bin, where it's accessible to all users, makes it problematic for those users, as it puts inaccessible files in their $PATH.

**Comment by jakebolam** [comment]
@torinthiel thanks for the report, great point. 

What are your thoughts on a fix? Some options that come to mind
- default install in ~/bin
- fallback if we can't install globally
- option to override install dir

**Comment by torinthiel** [comment]
The option is already there. just not documented - setting `YVM_ALIAS_DIR to any sensible value before installing works correcly.

However I wonder - given that the only thing we do with the target symlink is sourcing it from bash/zsh, why installing it somewhere, and not directly source from $HOME/.yvm (or whatever $YVM_DIR shows at point of installing)?

**Comment by torinthiel** [comment]
I could probably prepare a patch for this, but I doubt it'll be before Monday.

**Comment by jakebolam** [comment]
This sounds good to me. If you could put up a patch that would be 👍.

Monday is totally fine. Thanks so much @torinthiel
