### ISSUE TITLE
presence: distribute on package managers

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#206]
**Is your feature request related to a problem? Please describe.**
Add yvm to `brew install`

**Describe the solution you'd like**
See yvm available with brew

**Describe alternatives you've considered**

**Additional context**
- [x] Homebrew: `brew install tophat/bar/yvm`
- [ ] Npm - ❓
- [ ] Yum - ❓
- [ ] Apt - ❓

**Comment by jakebolam** [comment]
Thoughts @brandonbaksh @francoiscampbell ?

**Comment by francoiscampbell** [comment]
Yeah, that sounds amazing. Would solve the bootstrapping problem.

Let's also not forget about apt, yum, etc for linux

**Comment by yashshah** [comment]
If someone has not started on it yet, I would like to start working on this one.

**Comment by jakebolam** [comment]
All yours @yashshah

**Comment by jakebolam** [comment]
https://brew.sh/2019/02/02/homebrew-2.0.0/

**Comment by iamogbz** [comment]
@yashshah any updated on this?

**Comment by t--takai** [comment]
このIssueやって欲しいです。
I want this issue to be done.

`HomeBrew` でインストールできるようになると、
`direnv` で自動的にyarnのバージョンを切り替えられるようになります。
Once you can install with `HomeBrew` ,
You can switch the version of yarn automatically with `direnv` .

自動化はとても素晴らしいと考えていますので
実現されると嬉しい。
I think automation is so great ✨ 
I am happy to be realized.

Ref: https://github.com/direnv/direnv

**Comment by iamogbz** [comment]
@t--takai thanks for your interest! A first step has been made towards having `yvm` on `homebrew`. You can now install using `brew install tophat/bar/yvm`.

**Comment by t--takai** [comment]
@iamogbz 
それは素晴らしい！ 🎉  ありがとうございます。
一緒に働いている奴らにもそれを伝えておきます。
It's great! 🎉 Thank you very much.
I will tell them to those working with them.

**Comment by nrabinowitz** [comment]
I know this isn't a great bug report, but Homebrew installation did not work for me - it appeared to succeed without error, but it did not create a `~/.yvm` directory. Running the `configure-shell` script also succeeded without error, even though it pointed to a non-existent directory.

Homebrew also unnecessarily installed the latest Node, but that's less of an issue.

**Comment by iamogbz** [comment]
@nrabinowitz thanks! Could you please create an issue on the [tophat/homebrew-bar](https://github.com/tophat/homebrew-bar) repo, so we can track this? Some initial questions/clarifications. Homebrew pours yvm into a different folder that is created at time of first install (not the $HOME/.yvm), that's where `node yvm configure-shell` command would be run from. There's also a `--without-node` option that allows installation of yvm without node. Should probably only be used if node is not installed/managed by brew.

**Comment by derekedelaney** [comment]
I think the `--without-node` option should be in the docs for installing it. I ran into an issue where I was using nvm and it was conflicting with the version of node that got installed from brew.
