### ISSUE TITLE
test: automated testing of lowest supported node version (4.8)

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#208]
**Is your feature request related to a problem? Please describe.**
Add automated testing for our lowest supported version of node https://github.com/tophat/yvm/blob/master/webpack/webpack.config.base.js#L27

**Describe the solution you'd like**
Implement CI testing

**Describe alternatives you've considered**

**Additional context**

**Comment by iamogbz** [comment]
@jakebolam is still still open?
