### ISSUE TITLE
Should not output anything on starting new shell

### ISSUE THREAD

**Issue by torinthiel** [tophat/yvm#226]
**Is your feature request related to a problem? Please describe.**
After installation, when a user opens new shell, `yvm` displays the default `yarn` version. After some time this is getting unnecessary, and in some cases, when the executed shell is supposed to be non-interactive, may be problematic, as it may influence another program that is using the created shell.

**Describe the solution you'd like**
The message about currently selected version should be suppressed when initially loading `yvm`.

**Describe alternatives you've considered**
Current situation: Unnecessary, possibly harmful message.

**Additional context**

**Comment by jakebolam** [comment]
Way to find all the messages, yes should totally do this! @torinthiel

**Comment by torinthiel** [comment]
Sorry it took me so long - I had some strange mental block preventing me from doing it on weekend, and absolutely no time for two days.
