### ISSUE TITLE
decrease release size: minify node_modules/module bundling/tree shaking

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#233]
**Is your feature request related to a problem? Please describe.**
The release size of yvm.zip has jumped from 500KB to 6.7MB

**Describe the solution you'd like**
Decrease the release size. Possibly solutions (one or more)
- Minify node_modules
- Use a module bundler such as rollup
- tree-shake node_modules

**Describe alternatives you've considered**

**Additional context**
We moved away from webpack rolling up node_modules (PR:#215) to get ready to support GPG (PR: #131) and improve exec #111 (PR: https://github.com/tophat/yvm/pull/213).

**Comment by noahnu** [comment]
Why did we move away from rolling up node_modules? I've been reading through the GPG/exec issues linked in the context and am still a bit confused.
