### ISSUE TITLE
Removing YVM_ALIAS_DIR borked docker builds

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#240]
**Describe the bug**
Breaking change was released

**To Reproduce**
See screenshot

**Expected behavior**
We should bump the major verison of yvm to reflect a breaking change

**Screenshots**
![screen shot 2018-12-12 at 4 01 32 pm](https://user-images.githubusercontent.com/3534236/49898512-3e778500-fe27-11e8-84e5-f282e0053666.png)

**Comment by jakebolam** [comment]
@torinthiel I'm more just documenting this if people come looking for help. I know we spoke of this and we're ok with it

**Comment by jakebolam** [comment]
I'm thinking we should add documentation/support of installing a specific version of NPM with the install script, and adding documentation on how to pin version installs

**Comment by jakebolam** [comment]
p1 done in #256. (Support installing specific yvm versions)
p2: Will need to show support for pinning the version of `install.sh`.

**Comment by jakebolam** [comment]
Versioning support is here (see docs) and we're now doing semantic release (can signify breaking changes)

**Comment by iamogbz** [comment]
@jakebolam is this still open?
