### ISSUE TITLE
gh-release in dependencies (and not devDependencies)

### ISSUE THREAD

**Issue by torinthiel** [tophat/yvm#245]
**Describe the bug**
A dependency on `gh-release` is recorded in `package.json` in `dependencies` section. Given that the module is only used by the `scripts/release.js` I guess it should only be in `devDependencies`, it's not that a user is going to trigger github release.

Note that `gh-release` pulls a lot of transitive dependencies - the size of `node_modules_production` after running `make build-release` is 43MB, while after moving this to `devDependencies` it's only 17MB. The resulting `yvm.zip` is also down from 6.8MB to 3.1MB.

**To Reproduce**
1. Download yvm repository
2. Run `make build-production`
3. Check the size of `node_modules_production` and `artifacts/yvm.zip`.
4. Run `make clean`
5. Move `gh-release` from `dependencies` to `devDependencies` in `package.json`
6. Run `make build-production` again
7. Compare current sizes with those from point 3.

**Expected behavior**
A smallest needed set of dependencies is used.

**Desktop (please complete the following information):**
 - OS: linux
 - YVM 0.9.17
 - Shell: n/a
 - Node version: 10.14.2

**Additional context**
Note that possibly any automation using `scripts/release.js` or directly using `gh-release` may require fixing.

**Comment by jakebolam** [comment]
Great catch!
