### ISSUE TITLE
Logging to error stream by default

### ISSUE THREAD

**Issue by sanchitgera** [tophat/yvm#260]
**Describe the bug**
By default, our log function logs to the error stream using `console.error`, even for warnings and success messages. We need to change the default to the normal console and/or update all usages of the `log` method to either `log.info` or `log.warn`

See https://github.com/tophat/yvm/blob/22b44aea9506014ec04fd8000e95b4bae469dce7/src/util/log.js#

**Comment by jakebolam** [comment]
The motivation behind the current behavior is to allow programs to pipe data|capture content they want easily. E.g. `yvm list` only outputs the list part 'the capturable part'. We flag this in JS as `log.capturable`.
