### ISSUE TITLE
Provide a built-in fallback yarn version 

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#261]
**Is your feature request related to a problem? Please describe.**
Yvm does not work without a global version/.yvmrc file or version supplied on the command line

**Describe the solution you'd like**
Provide a built-in fallback version. I.e. if it can't find a version it will use yarn 1.7.2.

**Additional context**
Came about when discussing #258

**Comment by torinthiel** [comment]
We'd have to be able to somehow argument why this specific version and not the next one. Although I kind of like the idea if the default would be `--lts` (#175), this would be easy to defend.

However having it not use anything and displaying message about selecting default version has it's merits also - it'll at least give plain information that the default version can be set, and needs not be 'latest available' or whatever.
