### ISSUE TITLE
Decide how much we'd like to reassemble nvm

### ISSUE THREAD

**Issue by torinthiel** [tophat/yvm#262]
**Is your feature request related to a problem? Please describe.**
Given that `yvm` is a lot like `nvm` in purpose etc, I think we should make a decision how much we want to mimic `nvm` from user's point of view. 

There's a clean advantage of being very much nvm-like, there will be much less steep learning curve, and less surprises. However going this way means that we won't be able to make a lot of UI decisions, as nvm is already quite stable and probably in most cases they've already made a decision we're currently making.

**Additional context**
This would influence all our user-facing interface - command names and semantics, options etc.

**Comment by iamogbz** [comment]
I think this a good path to go down. There're a few things we'd have to change to match current nvm.
- [ ] Add `uninstall` substitute for `remove` command
- [ ] Replace `yvm version` with `yvm --version`
- [ ] Add support for `nvm` like aliases
  - Default aliases: current, default, latest, system
  - These can be used in place of version numbers in the commands
- [ ] Add `yvm current` which shows the current `yarn version`
  - Indicates if it is a system version i.e. not installed by `yvm`, using the alias
- [ ] Update `which` command to show the `path` (BREAKING CHANGE?)
- [ ] Remove implicit help command [`help [cmd]`](https://github.com/tj/commander.js/issues/683)
