### ISSUE TITLE
switch install.sh to javascript

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#266]
**Is your feature request related to a problem? Please describe.**
- install.sh depends on JS to run a few lines (e.g. https://github.com/tophat/yvm/blob/master/scripts/install.sh#L39)
- yvm requires javascript is installed

Why not make the install script JS too, installing would look like:
`/usr/bin/node -e "$(curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install)"`

Not only would it be easier to maintain, we could also write better unit test coverage around the install.

**Describe the solution you'd like**
Install script in javascript and docs referring to install commands like: `/usr/bin/node -e "$(curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install)"`

**Describe alternatives you've considered**
Keeping it in bash

**Comment by francoiscampbell** [comment]
FYI, you can still pipe to node: `curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install | node`
