### ISSUE TITLE
Unable to install version `1.1.0-exp.2`

### ISSUE THREAD

**Issue by yashshah** [tophat/yvm#271]
**Describe the bug**
Installing version `1.1.0-exp.2` fails. It is a valid version but currently yvm doesn't allow to install it. 

**To Reproduce**
1. `yvm i 1.1.0-exp.2`
2. See error

**Expected behavior**
It should install version `1.1.0-exp.2`

**Screenshots**
![image](https://user-images.githubusercontent.com/1558352/50420026-05450900-085a-11e9-9d22-740db974130b.png)

**Comment by jakebolam** [comment]
Thanks for catching this @yashshah !
