### ISSUE TITLE
Support .yarnversion file if .yvmrc is not present

### ISSUE THREAD

**Issue by lachlanhunt** [tophat/yvm#276]
**Is your feature request related to a problem? Please describe.**
Some other tools exist which use a .yarnversion file to indicate the version of yarn to use. YVM should be compatible with this existing practice.

**Describe the solution you'd like**
When .yvmrc is not present, yvm should look for a .yarnversion file instead

**Comment by jakebolam** [comment]
@lachlanhunt great idea! Do you want to try adding this? We use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for managing these things

Could possible change some config here: https://github.com/tophat/yvm/blob/master/src/util/version.js#L58
Using: https://github.com/davidtheclark/cosmiconfig#searchplaces
To get this working

**Comment by lachlanhunt** [comment]
I've got a branch with the fix locally. Can you add me as a contributor so I can push my branch, or would you prefer I fork the repo and make a PR from there?

**Comment by jakebolam** [comment]
@lachlanhunt is it ok if you fork the repo and add a PR? (CI is setup to run on forks)
