### ISSUE TITLE
yvm doesn't set the path properly inside of tmux

### ISSUE THREAD

**Issue by msrose** [tophat/yvm#283]
**Describe the bug**
yvm does not set the PATH correctly inside tmux

**To Reproduce**
1. Enter a directory with a .yvmrc that is different from your current yarn version
1. `yvm use && yarn -v` should show the same version as your .yvmrc
1. Do the above inside a tmux session
1. yvm does not change the yarn version

Here is my PATH outside of tmux: 
```
/Users/michaelrose/.yvm/versions/v1.7.0/bin:/Users/michaelrose/.yarn/bin:/Users/michaelrose/.config/yarn/global/node_modules/.bin:/Users/michaelrose/.avn/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/michaelrose/.pyenv/shims:/Users/michaelrose/.nvm/versions/node/v8.11.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
```

And here is my path inside tmux:
```
/Users/michaelrose/.yarn/bin:/Users/michaelrose/.config/yarn/global/node_modules/.bin:/Users/michaelrose/.avn/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/michaelrose/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michaelrose/.yvm/versions/v1.7.0/bin:/Users/michaelrose/.yarn/bin:/Users/michaelrose/.config/yarn/global/node_modules/.bin:/Users/michaelrose/.avn/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/michaelrose/.pyenv/shims:/Users/michaelrose/.nvm/versions/node/v8.11.3/bin:/usr/local/sbin:/usr/local/sbin
```

It seem like in tmux, .yarn/bin gets added to the path before .yvm/versions. It's possible I could configure something locally on my machine to make this work as expected, but thought I'd file an issue anyway for tracking purposes and in case anyone comes across the same behaviour and is wondering what is going on.

**Expected behavior**

yvm should behave the same both inside and outside of tmux

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - YVM Version: 1.0.9
 - Shell: bash
 - Node version: 8.11.3

**Comment by jakebolam** [comment]
@msrose any chance you could put up a PR for this?
