### ISSUE TITLE
Support loosely specified versions (package.json engines version format)

### ISSUE THREAD

**Issue by draperunner** [tophat/yvm#284]
It would be great to be able to specify the Yarn version more loosely, preferrably using the same format as in the engines property of package.json. (https://docs.npmjs.com/files/package.json#engines)

In my case, we use `yarn: 1.12` as our Yarn version in package.json engines. What I would like to do is to create a `.yvmrc.js` like this:

```
module.exports = require('./package.json').engines.yarn
```

in order to keep the yvm version in sync with the engine version. This works for specific versions, but gives me an error on `1.12` as yvm cannot infer the specific version to use.

It would maybe also be cool to have yvm use the engine version as fallback if there is no config file, as mentioned in #136, but I don't think this is the issue to discuss that. I just want to specify versions more loosely.

**Comment by draperunner** [comment]
Yes, I'll gladly have a go at it! :) I don't have much time this month though, but I'll give it a try in February.

**Comment by jakebolam** [comment]
@draperunner looking forward to it!
