### ISSUE TITLE
yvm exec does not proxy stdout/stdin correctly

### ISSUE THREAD

**Issue by msrose** [tophat/yvm#286]
**Describe the bug**
Discovered when using yvm exec to invoke commitizen:
![image](https://user-images.githubusercontent.com/3495264/51328936-6c617200-1a42-11e9-9e5e-fc5ec6b799ac.png)

**To Reproduce**
1. Invoke an interactive prompt, such as commitizen cli, using yvm exec e.g. `yvm exec git-cz`
2. Colours do not show up correctly; arrow key inputs do not propagate back to commitizen
3. Invoke the interactive prompt with yarn, such as `yarn git-cz`
4. Everything works as expected (colours show up and arrow keys get back to commitizen)

**Expected behavior**
Invoking node_modules executables with `yarn` and `yvm exec` should have the same behaviour

**Desktop (please complete the following information):**
 - OS: MacOS 10.4.2
 - YVM Version: 1.0.9
 - Shell: bash
 - Node version: 8.11.3

**Comment by jakebolam** [comment]
@msrose I've put up a PR to fix this. https://github.com/tophat/yvm/pull/290
Would you mind verifying?
