### ISSUE TITLE
cannot yvm use 1.14.0

### ISSUE THREAD

**Issue by albertywu** [tophat/yvm#315]
**Describe the bug**
`yvm use 1.14.0` does not select yarn 1.14.0

**To Reproduce**
1. yvm install 1.14.0 (works fine)
2. yvm use 1.14.0 (sets 1.12.3 instead -- see screenshot below)

**Expected behavior**
Expect yvm to use 1.14.0

**Screenshots**
![Screen Shot 2019-03-08 at 2 49 26 PM](https://user-images.githubusercontent.com/1920766/54060444-8fdaaa80-41b1-11e9-9784-5eb787c6df38.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - YVM Version: 2.4.0
 - Shell: bash
 - Node version: 10.15.3

**Additional context**
None

**Comment by noahnu** [comment]
I'm unable to recreate this on macOS Mojave 10.14.3, with bash via iterm2.

![yvm_bug_gif](https://user-images.githubusercontent.com/1297096/54074709-c83ac100-4263-11e9-82c8-3023d96fbce5.gif)

Maybe someone else has an idea for how to further debug?

**Comment by iamogbz** [comment]
@albertywu could not reproduce the behaviour as well. Maybe
- `yvm update-self` to reinstall the most recent yvm
- `export YVM_VERBOSE=1`
- `yvm use 1.14.0`

Please share the output, thanks!

**Comment by albertywu** [comment]
oh hmm, it looks like the `yarn` i had installed using `brew install yarn` was conflicting somehow. When I uninstalled that, everything works as expected.

**Comment by iamogbz** [comment]
@albertywu thanks for the follow up. YVM should do a better job of shimming the yarn version #283 #163.
