### ISSUE TITLE
How to use yvm inside docker image?

### ISSUE THREAD

**Issue by Bessonov** [tophat/yvm#316]
**Is your feature request related to a problem? Please describe.**
I'm not sure that this behavior is a bug or expected behavior.

**What I'm trying to do?**
For development I'm creating a docker image and install everything needed into it. It includes needed languages like java/maven (sdkman), node/npm (nvm), but also vim, vscode, eclipse, android (build) tools. With vagrant It improves onboarding time for developers and easy way to try out new versions of used tools. Now I want to add yarn and struggle with `yvm`. For example, the minimal Dockerfile:

```
FROM ubuntu:18.04

RUN apt-get update && apt-get -yqq install curl unzip

SHELL ["bash", "--login", "-c"]

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | PROFILE=~/.profile bash
RUN nvm install v10.15.3

RUN curl -fsSL https://raw.githubusercontent.com/tophat/yvm/v2.4.0/scripts/install.sh | sed 's/\.bashrc/\.profile/g' | INSTALL_VERSION="v2.4.0" bash
RUN yvm use 1.13.0
```
Because of non-interactive mode, I add initialization to `.profile` instead of `.bashrc`. But I get following error:

```
docker build --no-cache -t test .
[...]
Step 7/7 : RUN yvm use 1.13.0
 ---> Running in 928b75fe868c

  Usage: yvm [options] [command]

  Yarn Version Manager

  Options:

    -h, --help                        output usage information

  Commands:

    install|i [options] [version]     Install the specified version of Yarn.
[...]
    help [cmd]                        display help for [cmd]
bash: yvm: command not found
The command 'bash --login -c yvm use 1.13.0' returned a non-zero code: 127
```

You can add `-x` to `SHELL` to get more inside. It seems like yvm expects an argument in non-interactive mode even on initialization: `yvm_ 'script' $@`.

With interactive bash (`SHELL ["bash", "--login", "-i", "-c"]`) I can build image. But after creating a container there is no entry in PATH for yarn binary:
```
docker run --rm -it test bash --login
node --version
> v10.15.3
yvm version
> v2.4.0
yarn --version
> bash: yarn: command not found

env | grep PATH
> PATH=/root/.nvm/versions/node/v10.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

yvm use 1.13.0
> Now using yarn version 1.13.0
yarn --version
> 1.13.0
```

**Describe the solution you'd like**

It would be nice that `yvm` doesn't require interactive shell like `nvm` and global yarn version an be set. Furthermore, `yvm` should set/switch yarn version, if it discovers `.yvmrc` in current or parent folders.

**Describe alternatives you've considered**
No text.

**Additional context**
No text.

**Comment by noahnu** [comment]
Related / Possible duplicate: https://github.com/tophat/yvm/issues/240

> should set/switch yarn version, if it discovers .yvmrc in current or parent folders

There's an issue for that: #136 

---

Not to discourage discussion of non-interactive support, however:

You can call the shell script directly in your Dockerfile:

```
RUN curl $YVM_STATIC_REPO/v2.4.0/scripts/install.sh | YVM_ALIAS_DIR=$HOME bash
RUN $HOME/.yvm/yvm.sh install 1.13.0
```

Alternatively, I believe you want to do `bash --login -c 'yvm use 1.13.0'` rather than `bash --logic -c yvm use 1.13.0` (note the quotes). The latter will execute yvm and attempt to pass "use" and "1.13.0" as positional args into the shell executing "yvm", rather than passed to yvm itself.

I'm unsure, but perhaps with your current setup, `RUN 'yvm use 1.13.0'` might work?

**Comment by Bessonov** [comment]
Hey @noahnu, thank you very much for your answer! I'm not sure that #240 is related.

```
RUN curl $YVM_STATIC_REPO/v2.4.0/scripts/install.sh | YVM_ALIAS_DIR=$HOME bash
RUN $HOME/.yvm/yvm.sh install 1.13.0
```

This has same issue, because the problem isn't the installation of `yvm`, but initialization in `.bashrc`. It expects a parameter in non-interactive mode.

> Alternatively, I believe you want to do bash --login -c 'yvm use 1.13.0' rather than bash --logic -c yvm use 1.13.0 (note the quotes).

Nope. I don't do that. It's done by docker and it's working as expected (look at the same procedure for `nvm`). But I tried it:

```
bash: yvm use 1.13.0: command not found
The command 'bash --login -i -c 'yvm use 1.13.0'' returned a non-zero code: 127
```

And notice the difference between `nvm` (just working without workarounds) and `yvm`.

**Comment by iamogbz** [comment]
@Bessonov welcome to the community! As @noahnu said we're tracking discussions around auto switching yarn in issue 136.

About your main issue, I think refactoring the `yvm.sh` to not rely on interactive mode and function more like the `yvm.fish` (which is more akin to `nvm`) would solve the issue. PR's welcome, will probably be putting one up for it soon.

**Comment by iamogbz** [comment]
@Bessonov replacing the yvm install line with
```
RUN curl -fsSL https://raw.githubusercontent.com/tophat/yvm/v2.4.2/scripts/install.sh | sed 's/\.bashrc/\.profile/g' | INSTALL_VERSION="v2.4.2" bash
```
Should work

**Comment by Bessonov** [comment]
@iamogbz cool, many thanks! Not tested at a bigger scale, but it works!
