### ISSUE TITLE
Pre-flight checks for install script dependencies

### ISSUE THREAD

**Issue by mcataford** [tophat/yvm#326]
**Is your feature request related to a problem? Please describe.**
Depending on which system `yvm` is installed, the install script could fail due to missing dependencies. For example, the install script depends on `unzip`, which doesn't seem to be necessarily installed out-of-the-box in some systems (see #325). If such a dependency is unmet, the user gets an opaque shell script error message.

**Describe the solution you'd like**
Some sort of pre-install check that would look at whether dependencies necessary to make the install happen are installed. If all goes well, it can be silent, but if something is missing, the user should be notified so that they know exactly how to rectify the situation.

This would empower users to fix minor install issues that do not require code changes themselves.

**Describe alternatives you've considered**
Having the dependency list in the documentation, although that's not particularly useful since it would require a lot of manual labour to manual check if you have them all. This can be automated by the preferred solution.

**Additional context**
The pre-flight check should be agnostic to what package manager you use, ideally, otherwise we'll run in the same kind of issue, but during the preflight check.

**Comment by mcataford** [comment]
I've jotted down a basic approach for this: https://github.com/tophat/yvm/pull/327

External thoughts welcome.

**Comment by iamogbz** [comment]
Closed by #327
