### ISSUE TITLE
yvm must be sourced after node/nvm path - YVM Could not find node executable.

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#329]
**Is your feature request related to a problem? Please describe.**
Seeing error:
```
YVM Could not find node executable.
Please ensure your YVM env variables and sourcing are set below sourcing node/nvm in your .zshrc or .bashrc
```
![Screen Shot 2019-03-16 at 9 43 44 AM](https://user-images.githubusercontent.com/3534236/54476137-02f6a900-47d0-11e9-8ef1-01df05b2fa89.png)

My `.zshrc` has the following config.
![Screen Shot 2019-03-16 at 9 42 55 AM](https://user-images.githubusercontent.com/3534236/54476133-f83c1400-47cf-11e9-86cb-af1477bed0b0.png)

Placing yvm sourcing below the sourcing of nvm fixed the issue.

**Describe the solution you'd like**
Someway to ensure on install that that node is already installed?

*Gotcha* debugging steps in the documentation?

**Describe alternatives you've considered**
Leaving this issue for others to find

**Comment by iamogbz** [comment]
Not sure how we can enforce this. Some of it will be resolved now that we have a [brew](https://github.com/tophat/homebrew-bar#sommeliers) install option that has node as a dependency and once #301 is closed which requires node for the install script.

**Comment by iamogbz** [comment]
Closing this for now
