### ISSUE TITLE
Decouple node installer from local binaries

### ISSUE THREAD

**Issue by noahnu** [tophat/yvm#348]
**Is your feature request related to a problem? Please describe.**

Currently yvm installer is strongly coupled to POSIX compliant systems (mkdir/rm) and common \*nix binaries (curl/unzip). yarn has cross-platform support, so by further decoupling yvm from specific platforms, we can move towards better cross-platform support as well.

**Describe the solution you'd like**

Replace all calls to binaries (mkdir/rm/curl) with built-in node equivalents.

**Describe alternatives you've considered**

- Compiling the standalone installer script via webpack so that we can import other packages (we would still manage total bundle size to keep it below some threshold). This is what yarn does.
- Support a number of "unzip" binaries, using the first binary available on the system.

**Comment by iamogbz** [comment]
Thanks! @noahnu
