### ISSUE TITLE
Sourcing yvm.fish does not preserve existing $fish_user_paths

### ISSUE THREAD

**Issue by iamogbz** [tophat/yvm#353]
**Describe the bug**
`source $YVM_DIR/yvm.fish` on fish shell startup replaces all paths with yvm yarn path.

**To Reproduce**
1. Install fish shell `brew install fish`
2. Install yvm
3. Modify `~/.config/fish/config.fish` to have `$fish_user_paths` set before the yvm line
```fish
set -U fish_user_paths "/some/valid/path" $fish_user_paths
```
4. Restart shell
5. `echo $fish_user_paths` does not contain paths set before sourcing yvm

**Expected behavior**
Sourcing yvm should not replace existing paths in `$fish_user_paths`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - YVM Version: 3.0.0
 - Shell: fish
 - Node version: v8.11.3

**Additional context**

**Comment by eastenluis** [comment]
For all paths, you mean paths that are set to `$fish_user_paths`?

**Comment by iamogbz** [comment]
> For all paths, you mean paths that are set to `$fish_user_paths`?

Yeah, were you able to reproduce this?
