### ISSUE TITLE
The command `yvm install latest` fails 

### ISSUE THREAD

**Issue by chinnichaitanya** [tophat/yvm#359]
**Describe the bug**
Running `yvm install latest` fails with the following error message

```
You have provided an invalid version number. use "yvm ls-remote" to see valid versions.
Error: Invalid version number provided
```

**To Reproduce**
1. Install `yvm` using `brew install tophat/bar/yvm`.
2. Update `~/.zshrc` with the following lines,
```
export YVM_DIR="/usr/local/opt/yvm"
[ -r $YVM_DIR/yvm.sh ] && source $YVM_DIR/yvm.sh
```
3. Run `source ~/.zshrc`.
4. Run `yvm install latest` which throws the above mentioned error.

**Expected behavior**
Install the latest available version of `yarn`.

**Screenshots**
<img width="624" alt="Screenshot 2019-04-09 at 19 49 13" src="https://user-images.githubusercontent.com/6941024/55807896-a6518a00-5b00-11e9-89d8-5e232dc38fca.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave, version: 10.14.4
 - YVM Version: 2.4.1
 - Shell: zsh
 - Node version: v10.9.0

**Comment by iamogbz** [comment]
@chinnichaitanya the formula has been updated, you should be able to upgrade it using brew. We'll do some work to automate keeping the tap up to date.
