### ISSUE TITLE
Support yarn 1.17 branch

### ISSUE THREAD

**Issue by dbchristopher** [tophat/yvm#426]
**Is your feature request related to a problem? Please describe.**
I am working in a repo that requires the latest version of yarn (1.17.3 as of writing). The latest yarn version that YVM currently supports is 1.16.0

**Describe the solution you'd like**
Keep up to date with stable yarn versions

**Comment by iamogbz** [comment]
Thanks @dbchristopher for raising this! Should be resolved now

**Comment by dbchristopher** [comment]
Awesome, thanks so much for the speedy response and resolution @iamogbz!!
