### ISSUE TITLE
Allow use yvm in non-interactive mode

### ISSUE THREAD

**Issue by Bessonov** [tophat/yvm#427]
**Is your feature request related to a problem? Please describe.**
The workaround described in #316 doesn't work anymore (after 3.0.1?), because of hardcoded configuration in [configureShell.js](https://github.com/tophat/yvm/blob/2789af9/src/commands/configureShell.js#L60)

**Describe the solution you'd like**
Something like (pseudo-code):

```javascript
const configFiles = (process.env.BASH_INITIALIZER || '.bashrc .bash_profile').split(/ /)
while (!configured && configFiles.length > 0) {
  const configFile = configFiles.shift()
  if (fs.existsSync(configFile)) {
    configured = await ensureConfig(configFile, bashConfig)
  }
}
```

**Describe alternatives you've considered**
May be a non-interactive flag while installation.

**Additional context**
`-`

**Comment by iamogbz** [comment]
Thanks for raising this. We could have a `CONFIG_FILE` env variable for the install configure command used here
https://github.com/tophat/yvm/blob/master/scripts/install.js#L268-L274
and add a `configFile` variable for the `configureShell` command used here
https://github.com/tophat/yvm/blob/master/src/yvm.js#L148-L152
and https://github.com/tophat/yvm/blob/master/src/commands/configureShell.js#L106-L110

Definitely open to PRs to fix this
