### ISSUE TITLE
Support yarn 2/berry

### ISSUE THREAD

**Issue by Bessonov** [tophat/yvm#430]
**Is your feature request related to a problem? Please describe.**
Just ask to support https://github.com/yarnpkg/berry

**Comment by iamogbz** [comment]
As `berry` is still experimental and does not have versioned releases, not sure this will be added to `yvm`

You could technically

<details>
<summary> Use their <a href="https://yarnpkg.github.io/berry/getting-started/install">install process</a>
<pre>
yvm install stable
yarn policies set-version v2
</pre>
</summary>

```sh
$ yvm install stable

Installing yarn v1.17.3 in /Users/me/.yvm
Downloading...
Finished downloading yarn version 1.17.3
Validating...
GPG signature validated
Extracting...
Finished extracting yarn version 1.17.3
Installation successful
```
```sh
$ yarn --version

1.17.3
```
```sh
$ yarn policies set-version v2

Resolving v2 to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/emmanuelogbiziugbe/Sources/fe-thm/.yarn/releases/yarn-berry.js...
Updating /Users/emmanuelogbiziugbe/Sources/fe-thm/.yarnrc...
Done!
```
```sh
$ yarn --version

v2.0.0
```
</details>

**Comment by Bessonov** [comment]
> As berry is still experimental and does not have versioned releases, not sure this will be added to yvm

No problems :+1:

**Comment by iamogbz** [comment]
Will leave this open for discussion, maybe some expanding on your initial idea will be useful for someone

**Comment by DanielRuf** [comment]
Bump.

**Comment by iamogbz** [comment]
Holding off for now as berry is still in RC versions and does not support the same installation methods and yarn v1. Once v2 is fully released, will add to the list of yvm yarn versions.

**Comment by noahnu** [comment]
I'm not sure how compatible yarn v2 is with the paradigm yvm uses.

yarn 2 currently requires you to commit the yarn binary in your repo, which makes yvm redundant for yarn 2 versioning. Since yarn 2 is invoked via yarn 1, yvm is still useful there.

Related:
- https://github.com/yarnpkg/berry/issues/969
- https://github.com/nodejs/corepack

**Comment by balovbohdan** [comment]
> I'm not sure how compatible yarn v2 is with the paradigm yvm uses.
> 
> yarn 2 currently requires you to commit the yarn binary in your repo, which makes yvm redundant for yarn 2 versioning. Since yarn 2 is invoked via yarn 1, yvm is still useful there.
> 
> Related:
> 
> * [[Feature] Allow opting-out of vendoring berry's files yarnpkg/berry#969](https://github.com/yarnpkg/berry/issues/969)
> * https://github.com/nodejs/corepack

Good point...
