### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by iamogbz** [tophat/yvm#435]
**Is your feature request related to a problem? Please describe.**

`yvm` should be usable wherever `node` and `yarn` are installable.
Currently windows is not supported

**Describe the solution you'd like**

Shell scripts and yarn shim need to be built for windows as well as an installer that configures them

**Describe alternatives you've considered**

Distribute a docker container with `yvm` configured

**Additional context**

- https://github.com/zeit/pkg
- https://github.com/coreybutler/nvm-windows
- https://www.phpied.com/make-your-javascript-a-windows-exe/
- https://github.com/yarnpkg/yarn/blob/master/scripts/build-windows-installer.bat
- http://stat.sfu.ca/statgen/resources/r-tools-for-building-packages-on-windows.html
- https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd
- https://docs.microsoft.com/en-us/cpp/build/setting-the-path-and-environment-variables-for-command-line-builds

**Comment by mxmlnglt** [comment]
OK, thanks @iamogbz for posting this, a few weeks ago (before July 2019) I was searching for a way to install yvm on Windows and couldn't find anything (or didn't understand how I should do).

So unfortunately it seems like it's impossible. What a pity. :(

**Comment by iamogbz** [comment]
@mxmlnglt do not give up hope! Still investigating and adding more resource links. Should be possible without changing the way yvm works

**Comment by mxmlnglt** [comment]
> @mxmlnglt do not give up hope! Still investigating and adding more resource links. Should be possible without changing the way yvm works

You see? Bug has been closed as "wontfix". By the way, I don't work any more on Windows... so I don't bother.

**Comment by noahnu** [comment]
Closed as won't fix as we've deprecated yvm in favour of corepack which is built-in to nodejs.

**Comment by mxmlnglt** [comment]
> Closed as won't fix as we've deprecated yvm in favour of corepack which is built-in to nodejs.

Great... thanks for the tip! (btw I don't do JS regularly so... that's why I missed the news...)
