### ISSUE TITLE
Yvm use is using the global version instead of project root's  .yvmrc

### ISSUE THREAD

**Issue by nutboltu** [tophat/yvm#449]
**Describe the bug**
In my project, I added a `.yvmrc` with version `1.9.2` and also add engines.yarn `1.9.2` in the `package.json`. But if I run `yvm use` in the root directory it's using global yarn version(which is `1.17.3`) instead of `1.9.2`

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create a project using `npm init`. It will create a package.json for you.
2. Create a file `.yvmrc` in the same directory with version `1.9.2`
3. Run command: `yvm use`
4. It will use global yarn version instead of `.yvmrc` version.

**Expected behavior**
`yvm use` should pick the yarn version from `.yvmrc`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - YVM Version: `3.6.2`
 - Shell: zsh
 - Node version: 12.4.0

**Additional context**

**Comment by iamogbz** [comment]
Welcome @nutboltu! I'm unable to reproduce on my machine using a close enough config
```zsh
topper% cd sources
topper% mkdir test-yvm
topper% cd test-yvm
topper% npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-yvm)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to /Users/emmanuelogbiziugbe/Sources/test-yvm/package.json:

{
  "name": "test-yvm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes)
topper%
topper% echo '1.9.2' > .yvmrc
topper% which yarn
/Users/emmanuelogbiziugbe/.yvm/shim/yarn
topper% yvm use
Now using yarn version 1.9.2
topper% which yarn
/Users/emmanuelogbiziugbe/.yvm/versions/v1.9.2/bin/yarn
topper% yarn --version
1.9.2
topper% node --version
v12.3.0
topper%
```
Could you try reinstalling yvm and then in a new shell in the package directory
```sh
yvm unalias default
export YVM_VERBOSE=1
yvm use
```
And post here the outputs if failing

**Comment by nutboltu** [comment]
@iamogbz , I reinstalled `yvm` and run those command as you mentioned.
here's my output
<img width="593" alt="Screen Shot 2019-08-22 at 9 25 06 am" src="https://user-images.githubusercontent.com/9896958/63475059-c0dc3c80-c4be-11e9-8fd8-ffc92b68e6f8.png">

**Comment by nutboltu** [comment]
@iamogbz I found the issue. It's in the `package.json`'s `engines.yarn`.
If I use `~1.9.2` or `>=1.9.2 <1.9.4` then it works fine.
But if I use carret(^), then it breaks
```
"engines": {
    "yarn": "^1.9.2" // This ^ breaks the expected behaviour
  }
```

**Comment by iamogbz** [comment]
@nutboltu hi that's expected behaviour as the `^` indicates in semantic versioning to use the latest minor version. i.e. `^1.9.2` is equivalent to `>=1.9.2 <2.0.0` and so would match `1.17.3` but not `2.0.0`

**Comment by nutboltu** [comment]
It seems like we don't need `.yvmrc` if we have the engines set in our `package.json`. Thanks @iamogbz for your quick reply. Closing this issue.
