### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by iamogbz** [tophat/yvm#462]
This is a sensitive topic that we fully intend to treat with care. Our goal is to gain more insight into how the tool is used and some user demographic information from the following questions.

**Questions**

- Which commands are used and how often?
- How yarn versions are executed? i.e. `yvm use` or `yvm shim`
- In what environment is yvm used? e.g. CI, PC, servers etc.
- What projects are using yvm? project-name.git
- Which yarn version is most managed?

No PII or private logs will be used, only information that is willingly or publicly shared. This issue is for discussion on how this can be done transparently, non invasively and with complete control over what information is volunteered.

One idea is having an environment flag `YVM_ANALYTICS`, that can be set to `=false` to disable all logging or `=command,shimmed,project,version` to opt in for specific information sharing.

Please share thoughts below and take some time to fill out this [survey](https://docs.google.com/forms/d/e/1FAIpQLSfLCWaYyuuAIstYsCpoXwvW2ZVrP9jM2ckNwSKaKbGlEoJwdw/viewform) 🙏

**Comment by noahnu** [comment]
I'm not sure I see the value in having analytics built into the app. If we're curious about usage, it'd be better to encourage open discussion community. Potentially print a message on fresh installations only that points to the website and slack channel.
