### ISSUE TITLE
Fish shell: slow startup

### ISSUE THREAD

**Issue by agwhitaker93** [tophat/yvm#465]
**Describe the bug**
Sourcing ~/.yvm/yvm.fish is slow

**To Reproduce**
1. Install yvm
2. Add the following to your config.fish:
```
set -x YVM_DIR /home/$USER/.yvm    
. $YVM_DIR/yvm.fish
```
3. Run the command: `fish --profile prompt.prof -ic 'fish_prompt; exit'; sort -nk 1 prompt.prof`
4. Calls to `yvm.js get-old-path` and `yvm.js get-shim-path --shell=fish` take a lot more time to execute than any other command

**Expected behavior**
Calls to `yvm.js` should not take significantly longer than other setup commands

**Screenshots**
(header taken from the top of prompt.prof generated by the fish --profile command above)
```
Tim      Sum     Command
4008    4008    -----> env test "$__fish_sdkman_init" -nt "$__fish_sdkman_noexport_init"
4842    23085   -----------------> status stack-trace | grep called | cut -d " " -f 7
7161    7161    -------> xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2
8149    8149    ------------------> command grep --color=auto $argv
9371    9371    --> perl -I ~/perl5/lib/perl5/ -Mlocal::lib
9784    9784    --------------------> echo | command grep --color=auto "" >/dev/null 2>&1
20208   20208   -> systemctl --user is-active --quiet ssh-agent
188849  188849  ----------------------> /home/andrew/.nvm/versions/node/v10.16.3/bin/node /home/andrew/.yvm/yvm.js get-old-path
292826  292826  ---------------------> /home/andrew/.nvm/versions/node/v10.16.3/bin/node /home/andrew/.yvm/yvm.js get-shim-path --shell=fish
```

**Desktop (please complete the following information):**
 - OS: Manjaro 5.2.11-1
 - YVM Version: v3.6.2
 - Shell: fish v3.0.2
 - Node version: v10.16.3

**Additional context**
I'm using the following NVM wrapper: https://github.com/FabioAntunes/fish-nvm

**Comment by iamogbz** [comment]
@agwhitaker93 thank you for reporting this! Welcome any ideas or PRs on how to improve the performance of the script!
