### ISSUE TITLE
list-remote command not working

### ISSUE THREAD

**Issue by MattGoldwater** [tophat/yvm#466]
When I type yarn ls-remote or yarn list-remote I get the following error.
![image](https://user-images.githubusercontent.com/7827141/66260210-6ba77200-e770-11e9-9c3f-f86965934544.png)

I expected the command to "List Yarn versions available to install" as it says when I type yvm -h

I'm using yvm version 3.6.2, bash with oh my zsh, with Node v12.8.0 on a Mac using OSX 10.14.6

**Comment by iamogbz** [comment]
@MattGoldwater hi the `list-remote` command is on `yvm` not `yarn`.

<img width="339" alt="Screen Shot 2019-10-07 at 7 23 59 PM" src="https://user-images.githubusercontent.com/2528959/66338004-23d34700-e938-11e9-9496-d06008f87b8f.png">

We shim the `yarn` command but the options you can use on that must be `yarn` supported

<img width="454" alt="Screen Shot 2019-10-07 at 7 26 08 PM" src="https://user-images.githubusercontent.com/2528959/66338114-5ed57a80-e938-11e9-9a57-89ff1e118a39.png">

**Comment by MattGoldwater** [comment]
Whoops that’s presumably it. Thanks!
