### ISSUE TITLE
YVM doesn't play nicely with ASDF

### ISSUE THREAD

**Issue by jlurena** [tophat/yvm#481]
**Describe the bug**
When using ASDF to manage versions of nodejs YVM clobbers the path [here](https://github.com/tophat/yvm/blob/master/src/shell/yvm.sh#L8) causing ASDF to not reshim properly.

**To Reproduce**
Pre-req:

Need ASDF installed.
See https://github.com/asdf-vm/asdf/issues/572 for reproduction steps and more details

**Expected behavior**
Don't clobber path

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - YVM Version: 3.6.1
 - Shell: zsh
 - Node version: >= 8.9.4

Easy fix is to not overwrite the PATH https://github.com/tophat/yvm/blob/master/src/shell/yvm.sh#L8. But first I need to know why is this necessary?

**Comment by iamogbz** [comment]
@jlurena I suspect the issue is not from [`yvm.sh`](https://github.com/tophat/yvm/blob/master/src/shell/yvm.sh#L8) (that just exports the updated path) but rather here https://github.com/tophat/yvm/blob/76ab588d703719194f980d487f7710bb86684bdc/src/commands/getNewPath.js#L9-L15
This might be changing order of`PATH` entries due to the use of `Set`, although nodejs should preserve iterable order and just deduplicate entries...

Could you please share the contents of your `PATH` just after asdf (before yvm) and then after sourcing `yvm.sh`?

**Comment by jlurena** [comment]
Sure.

**Before YVM**
```
/Users/jlurena/.asdf/shims:/Users/jlurena/.asdf/bin:/Users/jlurena/.pyenv/shims:/Users/jlurena/bin:/Users/jlurena/.pyenv:/usr/local/bin:/usr/local/opt/mysql@5.6/bin:/Users/jlurena/Android/SDK/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/jlurena/.oh-my-zsh/custom/plugins/warhol/bin
```

**After**
```
/usr/local/Cellar/yvm/3.6.1/shim:/Users/jlurena/.asdf/installs/nodejs/8.9.4/bin:/Users/jlurena/.asdf/installs/nodejs/8.9.4/.npm/bin:/Users/jlurena/.asdf/shims:/Users/jlurena/.asdf/bin:/Users/jlurena/.pyenv/shims:/Users/jlurena/bin:/Users/jlurena/.pyenv:/usr/local/bin:/usr/local/opt/mysql@5.6/bin:/Users/jlurena/Android/SDK/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/jlurena/.oh-my-zsh/custom/plugins/warhol/bin
```

**The difference is**
```
/usr/local/Cellar/yvm/3.6.1/shim:/Users/jlurena/.asdf/installs/nodejs/8.9.4/bin:/Users/jlurena/.asdf/installs/nodejs/8.9.4/.npm/bin:
```

Seems YVM is explicitly adding nodejs 8.9.4 to the PATH

**Comment by iamogbz** [comment]
@jlurena hmm that's strange. YVM should know nothing about the ASDF nodejs/npm entries except it's in the PATH when the YVM script is executing.

**Comment by iamogbz** [comment]
Ah so the problem is that nodejs gets added to the PATH when the node script starts executing
```zsh
Last login: Thu Nov  7 23:38:33 on ttys002
Emmanuel@Book-of-Mac ~ % echo $PATH
/Users/Emmanuel/.asdf/shims:/usr/local/opt/asdf/bin:/Users/Emmanuel/Library/Android/sdk/platform-tools:/Users/Emmanuel/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Emmanuel@Book-of-Mac ~ % 
Emmanuel@Book-of-Mac ~ % which node
/Users/Emmanuel/.asdf/shims/node
Emmanuel@Book-of-Mac ~ % 
Emmanuel@Book-of-Mac ~ % 
Emmanuel@Book-of-Mac ~ % node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> 
> process.env.PATH
'/Users/Emmanuel/.asdf/installs/nodejs/12.10.0/bin:/Users/Emmanuel/.asdf/installs/nodejs/12.10.0/.npm/bin:/Users/Emmanuel/.asdf/shims:/usr/local/opt/asdf/bin:/Users/Emmanuel/Library/Android/sdk/platform-tools:/Users/Emmanuel/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
> 
```
So by the time `yvm` is generating the shimmed path it includes the prepended asdf node paths

**Comment by iamogbz** [comment]
As you said this is particular to the asdf yvm interaction... A possible fix would be to have yvm take the path to update from the parent shell script instead of using the child process

**Comment by jakebolam** [comment]
An application that relies on modifying the path, inside an application that relies on modifying the path 😂

Yeah, I wonder how to take the parent shell script

**Comment by jakebolam** [comment]
Does this affect other App's launched under ASDF I wonder?
