### ISSUE TITLE
fresh install of yvm, crashes under certain conditions

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#485]
**Describe the bug**
YVM has weird behaviour/doesn't work/crashes terminal under certain fresh install conditions

**To Reproduce**
1. Fresh install of yvm (delete all config files/versions etc)
1. Run `yarn install` in a directory that does not have a `.yvmrc` file (yvm will intercept the yarn call and setup a yarn version for the first time)
1. Now go to a project with a `.yvmrc` file with the same version as whatever yvm setup (currently 1.19.1)
1. `yvm ls` should give weird output, `yvm use` will crash the terminal, `yvm install` will fail

**Expected behavior**
yvm to work

**Screenshots**
(In directory with `.yvmrc` file with the contents `1.19.1`
<img width="460" alt="Screen Shot 2019-11-10 at 12 46 19 PM" src="https://user-images.githubusercontent.com/3534236/68548271-0b33d200-03b9-11ea-8575-0dd91be50e81.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.1
 - YVM Version: v3.6.2
 - Shell: zsh
 - Node version: v12.13.0

**Comment by iamogbz** [comment]
@jakebolam welcome back! Feel free to open up a PR if you get the chance!

**Comment by iamogbz** [comment]
@jakebolam unable to reproduce this.

<img width="741" alt="Screen Shot 2019-11-11 at 11 24 20 PM" src="https://user-images.githubusercontent.com/2528959/68641958-788b5400-04da-11ea-81e6-03e01b3c857a.png">
<img width="707" alt="Screen Shot 2019-11-11 at 11 24 34 PM" src="https://user-images.githubusercontent.com/2528959/68641964-7cb77180-04da-11ea-90de-8e4eee5ff905.png">

**Comment by jakebolam** [comment]
Heyo 👋 

I had a dig and I couldn't reproduce either now.

This was a fresh OS install. 

I also think there was a major OS upgrade to 10.15 in between too, e.g.:

1. install yvm
1. use yarn, let yvm install the version
1. Upgrade OS by a major version
1. Attempt to use `yvm use` in a project with an RC file.

Mac did change filesystem behaviour/permissions during this upgrade? (They've done a bunch of changes in this area).

Could also have been a flake 🤷‍♂
