### ISSUE TITLE
False Version don't match

### ISSUE THREAD

**Issue by OleksandrKucherenko** [tophat/yvm#486]
**Describe the bug**

```bash
yvm current
# 1.19.0
# Your .yvmrc version: >=1.19.0 and PATH version: 1.19.0 don't match :(
```

OR 

```bash
yvm current
1.19.1
Your .yvmrc version: >=1.19.0 and PATH version: 1.19.1 don't match :(
```

**To Reproduce**

`~/.zshrc`:

```
# Yarn Version Manager
export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
export YVM_DIR=/Users/oleksandr.kucherenko/.yvm

source ~/.yvm/yvm.sh
```

`package.json`:

```json
{
  ...
  "engines": {
    "yarn": ">=1.19.0",
    "node": ">=10.16.3"
  },
  ...
}
```

**Expected behavior**
should recognize `>=` syntax in `package.json` and properly validate version dependency

**Desktop (please complete the following information):**
 - OS: mac os 10.14.6
 - YVM Version: v3.6.2
 - Shell: zsh
 - Node version: v10.17.0

**Additional context**

**Comment by iamogbz** [comment]
@OleksandrKucherenko thanks for contributing! If you can also open a PR that would be welcome :)
