### ISSUE TITLE
Support a default version of yarn/commands

### ISSUE THREAD

**Issue by jakebolam** [tophat/yvm#56]
```
➜  yvm git:(yvm-which) yvm list
Checking for installed yarn versions...
Installed yarn versions:
  - v1.7.0

➜  yvm git:(yvm-which) yvm which
Checking yarn version
You don't have yvm version installed
```

If I've installed a version, it should default to that.

Seeing *You don't have yvm version installed*
I have YVM installed, but I don't have a yvmrc. Should we have the concept of a default version to use?

**Comment by brandonbaksh** [comment]
Please refer to #137
