### ISSUE TITLE
Support .bash_profile or .bashrc

### ISSUE THREAD

**Issue by jameskuizon1315** [tophat/yvm#568]
After doing this in my terminal:
`curl -s https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.js | node`

This would be the result:

![Screen Shot 2020-02-11 at 4 37 08 PM](https://user-images.githubusercontent.com/42020246/74221319-cf2c4800-4cec-11ea-90c5-54f35d9bca06.png)

I don't have FISH in my system and I don't want either. Can I use my existing `.bash_profile` or `.bashrc` instead?

Also in your "Removing" section in your documentation this was written:
![Screen Shot 2020-02-11 at 4 45 33 PM](https://user-images.githubusercontent.com/42020246/74221860-02bba200-4cee-11ea-9861-a29ea02e36d5.png)

I tried adding those lines in my `.bash_profile` to no avail. 

How can I make this work? Thank you. 

OSx: 10.13.6

**Comment by jameskuizon1315** [comment]
Fix it already.

I just change `/home` to `/Users`. Sorry my bad. But can we still add this in the README.md? Thanks.

**Comment by iamogbz** [comment]
@jameskuizon1315 unsure of the change you're requesting. Yvm on install tries to configure bash, zsh and fish, and only fails if all shells cannot be configured. Could possibly make that clearer? Open to PRs
