### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by spacejamjim** [tophat/yvm#590]
**Describe the bug**
Installing yvm with homebrew, editing zshrc, using yvm --version (or any command) results in error

**To Reproduce**
```brew install tophat/bar/yvm```
 - there is no .yvm in Home
 - There is a yvm dir in usr/local/opt symlinked to usr/local/Cellar/yvm/3.6.7

```vi ~/.zshrc```
add the following 2 lines:
```
export YVM_DIR=/usr/local/opt/yvm/
[ -r $YVM_DIR/yvm.sh ] && source $YVM_DIR/yvm.sh #lods yvm
```
also tried
```
export YVM_DIR=/usr/local/opt/yvm/
source $(brew --prefix yvm)/yvm.sh #this loads yvm
```
Close iTerm2, open iTerm2
```yvm --version``` 

See error
```
❯ yvm --version
/usr/local/Cellar/yvm/3.6.7/yvm.js:1
(function (exports, require, module, __filename, __dirname) { !function(e){var t={};function r(n){if(t[n])return t[n].exports;var i=t[n]={i:n,l:!1,exports:{}};return e[n].call(i.exports,i,i.exports,r),i.l=!0,i.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)r.d(n,i,function(t){return e[t]}.bind(null,i));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=427)}([function(

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

**Expected behavior**
yvm install latest, yvm list, yvm --help, yvm --version all should not result in same error. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - YVM Version:  assuming 3.6.7
 - Shell: zsh
 - Node version: v6.17.1 (npm v6.4.1) (changeable using nvm)
 - nvm version: 0.35.2

**Additional context**
When I remove the entries from .zshrc, `which yarn` yields `/usr/local/bin/yarn` and `yarn --verison` yields `1.19.1`. When the entires are in .zshrc, I receive the aforementioned error for `yarn --version` and `which yarn` yields `/usr/local/Cellar/yvm/3.6.7/shim/yarn`

Also tried:
`brew uninstall yvm`
`brew install yvm`
run command given by HomeBrew
`node "/usr/local/opt/yvm/yvm.js" configure-shell --yvmDir "/usr/local/opt/yvm"`
**Result**: Same error as before.. missing ) after argument list 

### **Solved**
My node wasn't >= 8.0 ....... oof

**Comment by iamogbz** [comment]
@spacejamjim I'm closing this as it seems the issue was an incompatible version of node
