### ISSUE TITLE
create a "current" symlink

### ISSUE THREAD

**Issue by kamil-augustyniak** [tophat/yvm#655]
**Is your feature request related to a problem? Please describe.**
I have to select a path to the current yarn version in Webstrom IDE. After the change version in .yvmrc, I have to change it too in Webstorm settings. If I would have a "current" symlink to the current yarn version, I could use it and I would forget about changing Webstorm settings. I would like to use the "Run configurations" feature with the correct node and yarn versions.

**Describe the solution you'd like**
yvm use will not, by default, create a "current" symlink. Set $YVM_SYMLINK_CURRENT to "true" to enable this behavior.

**Describe alternatives you've considered**

**Additional context**

**Comment by iamogbz** [comment]
@kamil-augustyniak `yvm` currently shims `yarn` (adding it to your `PATH`) which uses the `.yvmrc` file in the current directory. You should be able to just point your ide to `/Users/me/.yvm/shim/yarn`.

**Comment by kamil-augustyniak** [comment]
Webstorm appends `/bin/yarn.js` to  `/.yvm/shim/yarn` so I have '/.yvm/shim/yarn/bin/yarn.js' and it gets an error. But I've created symlink `/.yvm/shim/bin/yarn.js` to `/.yvm/shim/yarn` and it works. Thanks for the help. I'll close my issue.
