### ISSUE TITLE
Support versions variants

### ISSUE THREAD

**Issue by erickskrauch** [tophat/yvm#673]
**Is your feature request related to a problem? Please describe.**
I want to specify the version as `1.16.0|1.19.1`.

**Describe alternatives you've considered**
Right now I just pinned the version to `1.19.1`.

**Additional context**
Such versions range is needed to work with workspaces until https://github.com/yarnpkg/yarn/issues/7734 will be resolved.

**Comment by iamogbz** [comment]
@erickskrauch this should be possible with a slight change `1.16.0||1.19.1`

**Comment by erickskrauch** [comment]
Thanks!
