### ISSUE TITLE
yvm configure-shell does not add entry to bash_profile

### ISSUE THREAD

**Issue by noahnu** [tophat/yvm#753]
**Describe the bug**

Using the installer or running `yvm configure-shell` adds a `source yvm.sh` entry to `.bashrc` but _not_ to `.bash_profile`. This means the yvm command is not available in login shells.

**To Reproduce**

Using bash, run the installer. For  good measure, run `yvm configure-shell`.

**Expected behavior**

An entry should be added to `.bash_profile` so that the command is available on bash login.

**Desktop (please complete the following information):**

- OS: `Darwin 19.5.0 Darwin Kernel Version 19.5.0; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`
- YVM Version: v3.6.7
- Shell: bash
- Node: v12.16.1

**Additional Context**

Looking at the configure shell code, it tries various shell configs (.bashrc, .zshrc) in order and exits upon the first success. `.bashrc` is not a _replacement_ for `.bash_profile`, so it shouldn't exit early.

**Comment by torinthiel** [comment]
But also note that it's quite common to source `.bashrc` in `.bash_profile`, so we should take precautions against including twice.

**Comment by iamogbz** [comment]
@noahnu not sure I'd count this as a bug, since it was intentional. Also you can run `yvm configure-shell --profile=~/.bash_profile`. Although I see that was never added to the api documentation.

**Comment by noahnu** [comment]
Looking into this a bit more, this behaviour actually looks correct. It's OSX that is acting strange by using bash profile instead of bashrc. Apparently it can be configured for the terminal in OSX though

**Comment by iamogbz** [comment]
@noahnu feel free to close the issue.

**Comment by noahnu** [comment]
https://superuser.com/questions/320065/bashrc-not-sourced-in-iterm-mac-os-x
