### ISSUE TITLE
yvm releases should be available whenever direct dependencies are updated

### ISSUE THREAD

**Issue by noahnu** [tophat/yvm#771]
**Is your feature request related to a problem? Please describe.**

When direct dependencies of yvm are updated, for example a security vulnerability fix, currently we don't release a new version of yvm with the fixes in the yvm.js bundle.

**Describe the solution you'd like**

Update the release infrastructure to release on any direct dependency change. Might be able to tweak dependabot to use a different commit message prefix?

**Comment by iamogbz** [comment]
I agree in the case of security vuln fixes but not the others. There's no need to cut a release if the user space has not effectively changed. Will look into the vuln case.
