### ISSUE TITLE
YVM fails ungracefully when git merge conflicts exist in package.json

### ISSUE THREAD

**Issue by justin808** [tophat/yvm#926]
**Describe the bug**
YVM fails ungracefully when git merge conflicts exist in package.json

**To Reproduce**
Rebase and have merge conflicts in pacakage.json

**Expected behavior**
don't crash when running `yarn use`

print message that package.json can't be parsed

killing shell is horrible as there are no messages

**Desktop (please complete the following information):**
 - OS:  MacOS 11.2
 - YVM Version: 4.1.1
 - Shell: zsh
 - Node version: 14.15.0

**Additional context**
* a new shell to the directory or cd to the directory that automatically run yvm use will abruptly close the shell
* debugged by manually merging conflicts in package.json

**Comment by noahnu** [comment]
Confirmed I can reproduce. Investigating...

**Comment by noahnu** [comment]
We delegate reading the file to cosmiconfig here: https://github.com/tophat/yvm/blob/08c40ab427a6c7253ca2910ecdb0af32eb71516d/src/util/version.js#L101.

I'd argue at the core this is a https://github.com/davidtheclark/cosmiconfig bug. On failure to read a file it should move on. At a minimum we can definitely fail more gracefully.
