### ISSUE TITLE
Can't use engines in package.json with yarn 2 and yvm

### ISSUE THREAD

**Issue by Ex4l** [tophat/yvm#998]
**Describe the bug**
I'm using Yarn 2.2.4 in my project and setup it following yarn official documentation:

> Using their [install process](https://yarnpkg.com/getting-started/install#updating-to-the-latest-versions)
> yvm install stable
> yarn policies set-version v2

Now I'm using the engines key in package.json but when i set my version to the one I'm using (2.4.2), I get this error message :

Given version can not be satisfied by yarn: ^2.4.2
See list of available yarn versions using: 'yvm list-remote'
No yarn version supplied!

**To Reproduce**
1. Setup yvm
2. Install latest stable
3. Set yarn to 2.2.4 using comand `yarn policies set-version 1.13.0`
4. Add engines object in your package.json:

`  "engines": {
    "npm": "^6.14.13",
    "yarn": "^2.4.2",
    "node": "^14.17.0"
  },`
  
  5. Launch yarn --version to get the error

**Expected behavior**
yarn working and not saying my version is not the good one.

**Screenshots**
![image](https://user-images.githubusercontent.com/5011287/124758528-f3ff0c00-df2e-11eb-8196-535443d5189e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu WSL inside Windows 10:
        Distributor ID: Ubuntu
        Description:    Ubuntu 20.04.2 LTS
        Release:        20.04
        Codename:       focal
 - YVM Version: v4.1.4
 - Shell: zsh
 - Node version: v14.17.0

**Comment by noahnu** [comment]
> Set yarn to 2.2.4 using comand yarn policies set-version 1.13.0

Do you mean `yarn set version`? policies is from yarn v1

If using yarn v2 (or even v3), you don't need to set the yarn version in "engines" as it's committed to your repository via `yarn set version`. In this case, we haven't determined the best path forward for yvm. -- Open to ideas.

In my Yarn 2 projects, I set the `.yvmrc` to `1.22.10` and then just use `yarn set version 2.4.1` and commit the binary. It seems to work fine since Yarn v2+ is launched via Yarn v1, which means you can use yvm to launch the Yarn v1 version which ultimately launches Yarn v2+.

**Comment by Ex4l** [comment]
> > Set yarn to 2.2.4 using comand yarn policies set-version 1.13.0
> 
> Do you mean `yarn set version`? policies is from yarn v1
> 
> If using yarn v2 (or even v3), you don't need to set the yarn version in "engines" as it's committed to your repository via `yarn set version`. In this case, we haven't determined the best path forward for yvm. -- Open to ideas.
> 
> In my Yarn 2 projects, I set the `.yvmrc` to `1.22.10` and then just use `yarn set version 2.4.1` and commit the binary. It seems to work fine since Yarn v2+ is launched via Yarn v1, which means you can use yvm to launch the Yarn v1 version which ultimately launches Yarn v2+.

Yeah it's yarn set version, sorry.

Yes indeed it's commited with the repository and configured in the yarnrc :)
